apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-policy-gateway
  namespace: tenant-gateway
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/example-tenant-policy-gateway-role
